import 'package:flutter/material.dart';
import '../../app/theme.dart';
import '../../core/widgets/merc_widgets.dart';
import '../../models/listing.dart';
import '../checkout/checkout_screen.dart';

class ListingDetailScreen extends StatefulWidget { final Listing listing; const ListingDetailScreen({super.key,required this.listing}); @override State<ListingDetailScreen> createState()=>_ListingDetailScreenState(); }
class _ListingDetailScreenState extends State<ListingDetailScreen>{ bool following=false;
 @override Widget build(BuildContext c){final x=widget.listing;return Scaffold(appBar:AppBar(title:const Text('Affare',style:TextStyle(fontWeight:FontWeight.w900)),actions:[IconButton(onPressed:()=>setState(()=>following=!following),icon:Icon(following?Icons.favorite_rounded:Icons.favorite_border_rounded,color:following?MercDealTheme.green:null))]),body:ListView(padding:const EdgeInsets.fromLTRB(18,4,18,30),children:[
  Container(height:260,decoration:BoxDecoration(borderRadius:BorderRadius.circular(28),gradient:const LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[Color(0xFF15384C),Color(0xFF08131F)]),border:Border.all(color:Colors.white.withValues(alpha:.06))),child:Center(child:Icon(x.icon,size:104,color:MercDealTheme.green))),const SizedBox(height:16),
  Row(children:[Expanded(child:Text(x.title,style:const TextStyle(fontSize:26,fontWeight:FontWeight.w900))),if(x.verifiedSeller)const Icon(Icons.verified_rounded,color:MercDealTheme.green)]),Text('${x.category} · ${x.location}',style:const TextStyle(color:Colors.white38)),const SizedBox(height:15),
  if(x.mode==SaleMode.descendingAuction)_auction(x) else _price(x),const SizedBox(height:14),
  Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:MercDealTheme.card,borderRadius:BorderRadius.circular(20)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('🟢 Venditore verificato',style:TextStyle(color:MercDealTheme.green,fontWeight:FontWeight.w900)),const SizedBox(height:7),Text('Condizioni: ${_condition(x.condition)}',style:const TextStyle(color:Colors.white60)),const SizedBox(height:5),Text(x.inShowcase?'💎 In Vetrina · 7 giorni':'MercDeal Protection disponibile',style:const TextStyle(color:Colors.white60))])),const SizedBox(height:14),
  Row(children:[Expanded(child:GlowButton(label:'Fai un’offerta',icon:Icons.handshake_rounded,secondary:true,onPressed:()=>_offer(c,x))),const SizedBox(width:9),Expanded(child:GlowButton(label:'Compralo',icon:Icons.shopping_cart_checkout_rounded,onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>CheckoutScreen(listing:x)))))])
 ]));}
 Widget _auction(Listing x)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(borderRadius:BorderRadius.circular(22),gradient:const LinearGradient(colors:[Color(0xFF0E2B28),Color(0xFF0B1C2B)]),border:Border.all(color:MercDealTheme.green.withValues(alpha:.2))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('📉 ASTA AL RIBASSO',style:TextStyle(color:MercDealTheme.green,fontWeight:FontWeight.w900,letterSpacing:1)),const SizedBox(height:5),Text('€${x.price.toStringAsFixed(2).replaceAll('.',',')}',style:const TextStyle(fontSize:38,fontWeight:FontWeight.w900)),const Text('−€0,20 al giorno · minimo del venditore nascosto',style:TextStyle(color:Colors.white38,fontSize:11)),const SizedBox(height:14),ClipRRect(borderRadius:BorderRadius.circular(8),child:LinearProgressIndicator(value:x.progress,minHeight:8,backgroundColor:Colors.white10,color:MercDealTheme.green)),const SizedBox(height:10),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('Partenza €${x.startPrice.toStringAsFixed(2).replaceAll('.',',')}',style:const TextStyle(color:Colors.white30,fontSize:10)),Text('${x.followers} persone la seguono',style:const TextStyle(color:Colors.white60,fontSize:10,fontWeight:FontWeight.w700))])]));
 Widget _price(Listing x)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:MercDealTheme.card,borderRadius:BorderRadius.circular(22)),child:Text('€${x.price.toStringAsFixed(2).replaceAll('.',',')}',style:const TextStyle(fontSize:38,fontWeight:FontWeight.w900)));
 String _condition(ListingCondition c)=>switch(c){ListingCondition.newItem=>'Nuovo',ListingCondition.excellent=>'Ottime condizioni',ListingCondition.good=>'Buone condizioni',ListingCondition.fair=>'Condizioni discrete'};
 void _offer(BuildContext c,Listing x){final ctl=TextEditingController();showModalBottomSheet(context:c,isScrollControlled:true,backgroundColor:MercDealTheme.card,builder:(_)=>Padding(padding:EdgeInsets.fromLTRB(18,18,18,MediaQuery.of(c).viewInsets.bottom+20),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Fai un’offerta',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:7),const Text('Prima di inviare vedrai sempre spedizione e totale.',style:TextStyle(color:Colors.white38)),const SizedBox(height:13),TextField(controller:ctl,keyboardType:TextInputType.number,decoration:const InputDecoration(prefixText:'€ ',hintText:'Importo')),const SizedBox(height:13),GlowButton(label:'Continua al riepilogo',icon:Icons.arrow_forward_rounded,onPressed:()=>Navigator.pop(c))])));}
}
