import 'package:flutter/material.dart';
import '../../app/theme.dart';
import '../../core/widgets/merc_widgets.dart';
import '../../models/listing.dart';
import '../shipping/shipping_screen.dart';
import '../meetup/meetup_screen.dart';

class CheckoutScreen extends StatefulWidget { final Listing listing; const CheckoutScreen({super.key,required this.listing}); @override State<CheckoutScreen> createState()=>_CheckoutScreenState(); }
class _CheckoutScreenState extends State<CheckoutScreen>{ int delivery=0; final cap=TextEditingController(); @override void dispose(){cap.dispose();super.dispose();}
 @override Widget build(BuildContext c){const shipping=5.90; final total=widget.listing.price+shipping;return Scaffold(appBar:AppBar(title:const Text('Checkout',style:TextStyle(fontWeight:FontWeight.w900))),body:ListView(padding:const EdgeInsets.fromLTRB(18,8,18,30),children:[Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:MercDealTheme.card,borderRadius:BorderRadius.circular(20)),child:Row(children:[Container(width:65,height:65,decoration:BoxDecoration(color:MercDealTheme.card2,borderRadius:BorderRadius.circular(16)),child:Icon(widget.listing.icon,color:MercDealTheme.green,size:32)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(widget.listing.title,style:const TextStyle(fontWeight:FontWeight.w900)),Text('€${widget.listing.price.toStringAsFixed(2).replaceAll('.',',')}',style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900))]))])),const SizedBox(height:15),const Text('Come vuoi riceverlo?',style:TextStyle(fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:9),_choice(0,Icons.local_shipping_outlined,'Spedizione','Costo visibile prima del pagamento · da €5,90'),_choice(1,Icons.location_on_outlined,'Ritiro a mano','Pagamento direttamente al ritiro'),if(delivery==0)...[const SizedBox(height:12),TextField(controller:cap,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'CAP di destinazione',prefixIcon:Icon(Icons.location_on_outlined))),const SizedBox(height:8),const Text('Il costo definitivo dipende da destinazione, peso, dimensioni e servizio scelto.',style:TextStyle(color:Colors.white38,fontSize:11))],const SizedBox(height:17),Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xFF102B25),borderRadius:BorderRadius.circular(20)),child:Column(children:[_row('Articolo','€${widget.listing.price.toStringAsFixed(2).replaceAll('.',',')}'),if(delivery==0)_row('Spedizione','€${shipping.toStringAsFixed(2).replaceAll('.',',')}'),const Divider(color:Colors.white10),_row('Totale',delivery==0?'€${total.toStringAsFixed(2).replaceAll('.',',')}':'€${widget.listing.price.toStringAsFixed(2).replaceAll('.',',')}',big:true)])),const SizedBox(height:14),const Row(children:[Icon(Icons.shield_outlined,color:MercDealTheme.green,size:20),SizedBox(width:8),Expanded(child:Text('Pagamento protetto secondo le regole dell’ordine.',style:TextStyle(color:Colors.white60,fontSize:12,fontWeight:FontWeight.w700)))]),const SizedBox(height:16),GlowButton(label:delivery==0?'Conferma e paga':'Continua con ritiro a mano',icon:Icons.lock_rounded,onPressed:()=>delivery==0?Navigator.push(c,MaterialPageRoute(builder:(_)=>const ShippingScreen())):Navigator.push(c,MaterialPageRoute(builder:(_)=>const MeetupScreen()))) ])));}
 Widget _choice(int v,IconData i,String t,String s)=>GestureDetector(onTap:()=>setState(()=>delivery=v),child:Container(margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:delivery==v?MercDealTheme.green.withValues(alpha:.08):MercDealTheme.card,borderRadius:BorderRadius.circular(18),border:Border.all(color:delivery==v?MercDealTheme.green.withValues(alpha:.4):Colors.white.withValues(alpha:.05))),child:Row(children:[Icon(i,color:delivery==v?MercDealTheme.green:Colors.white54),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontWeight:FontWeight.w900)),Text(s,style:const TextStyle(color:Colors.white38,fontSize:11))])),Icon(delivery==v?Icons.radio_button_checked:Icons.radio_button_off,color:delivery==v?MercDealTheme.green:Colors.white24)]));
 Widget _row(String a,String b,{bool big=false})=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(children:[Expanded(child:Text(a,style:TextStyle(color:big?Colors.white:Colors.white54,fontWeight:big?FontWeight.w900:FontWeight.w500))),Text(b,style:TextStyle(fontSize:big?21:14,fontWeight:big?FontWeight.w900:FontWeight.w700,color:big?MercDealTheme.green:Colors.white))]));
}
