import 'dart:async';
import 'package:flutter/material.dart';
import 'theme.dart';
import '../features/home/home_screen.dart';import '../features/search/search_screen.dart';import '../features/selling/sell_screen.dart';import '../features/messages/messages_screen.dart';import '../features/profile/profile_screen.dart';
class MercDealApp extends StatelessWidget{const MercDealApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'MercDeal',theme:MercDealTheme.dark(),home:const MercDealSplash());}
class MainShell extends StatefulWidget{const MainShell({super.key});@override State<MainShell> createState()=>_MainShellState();}
class _MainShellState extends State<MainShell>{int index=0;final pages=const[HomeScreen(),SearchScreen(),SellScreen(),MessagesScreen(),ProfileScreen()];@override Widget build(BuildContext c)=>Scaffold(body:IndexedStack(index:index,children:pages),bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(v)=>setState(()=>index=v),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home_rounded),label:'Home'),NavigationDestination(icon:Icon(Icons.search_rounded),label:'Cerca'),NavigationDestination(icon:Icon(Icons.add_circle_outline_rounded,size:30),selectedIcon:Icon(Icons.add_circle_rounded,size:32),label:'Vendi'),NavigationDestination(icon:Icon(Icons.chat_bubble_outline_rounded),selectedIcon:Icon(Icons.chat_bubble_rounded),label:'Messaggi'),NavigationDestination(icon:Icon(Icons.person_outline_rounded),selectedIcon:Icon(Icons.person_rounded),label:'Profilo')]));}
class MercDealSplash extends StatefulWidget{const MercDealSplash({super.key});@override State<MercDealSplash> createState()=>_MercDealSplashState();}
class _MercDealSplashState extends State<MercDealSplash>{@override void initState(){super.initState();Timer(const Duration(milliseconds:1100),(){if(mounted)Navigator.of(context).pushReplacement(MaterialPageRoute(builder:(_)=>const MainShell()));});}@override Widget build(BuildContext c)=>Scaffold(body:Container(decoration:const BoxDecoration(gradient:LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[Color(0xFF020B12),Color(0xFF061B22),Color(0xFF020D18)])),child:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Container(width:108,height:108,padding:const EdgeInsets.all(13),decoration:BoxDecoration(borderRadius:BorderRadius.circular(32),color:MercDealTheme.surface,border:Border.all(color:MercDealTheme.green.withValues(alpha:.6)),boxShadow:[BoxShadow(color:MercDealTheme.green.withValues(alpha:.22),blurRadius:45)]),child:Image.asset('assets/icon/app_icon.png')),const SizedBox(height:22),const Text('MercDeal',style:TextStyle(fontSize:39,fontWeight:FontWeight.w900)),const SizedBox(height:4),const Text('Il prezzo scende. L’affare sale.',style:TextStyle(color:Colors.white60,fontWeight:FontWeight.w700))]))));}
