import 'package:flutter/material.dart';
import '../../app/theme.dart';
import '../../core/widgets/merc_widgets.dart';

class SellScreen extends StatefulWidget { const SellScreen({super.key}); @override State<SellScreen> createState()=>_SellScreenState(); }
class _SellScreenState extends State<SellScreen>{
  int mode=1,duration=30; bool shipping=true,pickup=true,auth=false;
  final title=TextEditingController(); final price=TextEditingController(text:'80'); final min=TextEditingController(text:'65'); final weight=TextEditingController(text:'1,0'); final dims=TextEditingController(text:'30 × 20 × 10');
  @override void dispose(){title.dispose();price.dispose();min.dispose();weight.dispose();dims.dispose();super.dispose();}
  @override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(18,18,18,32),children:[
    Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Vendi su MercDeal',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),Text('Trasforma un oggetto in un affare.',style:TextStyle(color:Colors.white54))])),Container(width:45,height:45,decoration:BoxDecoration(color:MercDealTheme.green.withValues(alpha:.12),shape:BoxShape.circle),child:const Icon(Icons.sell_rounded,color:MercDealTheme.green))]),const SizedBox(height:18),
    Container(height:145,decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:const LinearGradient(colors:[Color(0xFF102E3D),Color(0xFF0B1826)]),border:Border.all(color:Colors.white.withValues(alpha:.06))),child:const Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.add_photo_alternate_outlined,size:43,color:MercDealTheme.green),SizedBox(height:8),Text('Aggiungi foto',style:TextStyle(fontWeight:FontWeight.w900)),Text('Fino a 12 foto · video imballaggio dopo la vendita',style:TextStyle(color:Colors.white38,fontSize:11))])),const SizedBox(height:14),
    TextField(controller:title,decoration:const InputDecoration(labelText:'Titolo annuncio',hintText:'Es. Sony Alpha 7 III')),const SizedBox(height:18),
    const Text('Scegli come vendere',style:TextStyle(fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:10),
    ...[_modeCard(0,Icons.shopping_cart_checkout_rounded,'Compralo subito','Un prezzo chiaro. L’acquirente compra subito.'),_modeCard(1,Icons.trending_down_rounded,'Asta al ribasso','Il prezzo scende di €0,20 ogni giorno.'),_modeCard(2,Icons.handshake_rounded,'Proposta libera','Lascia che siano le offerte a far partire la trattativa.')],
    const SizedBox(height:14),TextField(controller:price,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Prezzo',prefixText:'€ ')),
    if(mode==1)...[const SizedBox(height:12),TextField(controller:min,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Prezzo minimo · nascosto agli acquirenti',prefixText:'€ ')),const SizedBox(height:12),const Text('Durata asta',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:8),Wrap(spacing:8,children:[for(final d in [7,15,30])ChoiceChip(label:Text('$d giorni'),selected:duration==d,onSelected:(_)=>setState(()=>duration=d))]),const SizedBox(height:8),Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:MercDealTheme.green.withValues(alpha:.08),borderRadius:BorderRadius.circular(14)),child:const Row(children:[Icon(Icons.auto_graph_rounded,color:MercDealTheme.green,size:18),SizedBox(width:8),Expanded(child:Text('Il prezzo scende automaticamente di €0,20 al giorno, fino al tuo minimo.',style:TextStyle(color:MercDealTheme.green,fontSize:12,fontWeight:FontWeight.w700)))]))],
    const SizedBox(height:18),const Text('Consegna',style:TextStyle(fontSize:19,fontWeight:FontWeight.w900)),SwitchListTile(contentPadding:EdgeInsets.zero,value:shipping,onChanged:(v)=>setState(()=>shipping=v),activeThumbColor:MercDealTheme.green,title:const Text('Spedizione'),subtitle:const Text('Il costo reale sarà calcolato da destinazione, peso e dimensioni.')),if(shipping)Row(children:[Expanded(child:TextField(controller:weight,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Peso kg'))),const SizedBox(width:9),Expanded(child:TextField(controller:dims,decoration:const InputDecoration(labelText:'Dimensioni cm')))]),SwitchListTile(contentPadding:EdgeInsets.zero,value:pickup,onChanged:(v)=>setState(()=>pickup=v),activeThumbColor:MercDealTheme.green,title:const Text('Ritiro a mano'),subtitle:const Text('Il punto d’incontro viene scelto dal venditore dopo l’acquisto.')),SwitchListTile(contentPadding:EdgeInsets.zero,value:auth,onChanged:(v)=>setState(()=>auth=v),activeThumbColor:MercDealTheme.green,title:const Text('MercDeal Authenticity'),subtitle:const Text('Disponibile per categorie e marchi supportati.')),const SizedBox(height:12),GlowButton(label:'Vedi anteprima',icon:Icons.visibility_rounded,onPressed:()=>_preview(c))
  ]));
  Widget _modeCard(int v,IconData icon,String title,String sub)=>GestureDetector(onTap:()=>setState(()=>mode=v),child:AnimatedContainer(duration:const Duration(milliseconds:180),margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:mode==v?MercDealTheme.green.withValues(alpha:.09):MercDealTheme.card,borderRadius:BorderRadius.circular(18),border:Border.all(color:mode==v?MercDealTheme.green.withValues(alpha:.45):Colors.white.withValues(alpha:.05))),child:Row(children:[Icon(icon,color:mode==v?MercDealTheme.green:Colors.white54),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontWeight:FontWeight.w900)),Text(sub,style:const TextStyle(color:Colors.white38,fontSize:11))])),Icon(mode==v?Icons.radio_button_checked:Icons.radio_button_off,color:mode==v?MercDealTheme.green:Colors.white24)])));
  void _preview(BuildContext c)=>showModalBottomSheet(context:c,isScrollControlled:true,backgroundColor:MercDealTheme.card,builder:(_)=>Padding(padding:const EdgeInsets.fromLTRB(18,20,18,28),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Anteprima',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text(title.text.isEmpty?'Il tuo prossimo affare':title.text,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:6),Text(mode==1?'📉 Asta al ribasso · −€0,20/giorno':mode==0?'🛒 Compralo subito':'🤝 Proposta libera',style:const TextStyle(color:MercDealTheme.green,fontWeight:FontWeight.w800)),const SizedBox(height:7),Text('€${price.text} · ${mode==1?duration:0}${mode==1?' giorni':''}',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:15),GlowButton(label:'Pubblica dopo verifica venditore',icon:Icons.verified_user_outlined,onPressed:()=>Navigator.pop(c))])));
}
