import 'package:flutter/material.dart';
import '../../app/theme.dart';
import '../../core/widgets/merc_widgets.dart';
import '../auth/auth_screen.dart';
import '../listing/listing_detail_screen.dart';
import '../../models/listing.dart';

class SellScreen extends StatefulWidget {
  const SellScreen({super.key});
  @override State<SellScreen> createState() => _SellScreenState();
}
class _SellScreenState extends State<SellScreen> {
  int step=0, mode=1; bool ship=true, pickup=true; double start=80, minimum=65, drop=.20;
  final title=TextEditingController();
  @override void dispose(){title.dispose();super.dispose();}
  @override Widget build(BuildContext context){
    return SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(16,16,16,30),children:[
      Row(children:[const Expanded(child:Text('Vendi',style:TextStyle(fontSize:29,fontWeight:FontWeight.w900))),IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const AuthScreen())),icon:const Icon(Icons.verified_user_outlined))]),
      const Text('Pubblica il tuo annuncio in pochi passaggi.',style:TextStyle(color:Colors.white54)),const SizedBox(height:18),_progress(),const SizedBox(height:18),
      if(step==0)_stepProduct() else if(step==1)_stepMode() else _stepPrice(),
    ]));
  }
  Widget _progress()=>Row(children:[for(int i=0;i<3;i++)... [Expanded(child:Container(height:6,decoration:BoxDecoration(color:i<=step?MercDealTheme.green:Colors.white12,borderRadius:BorderRadius.circular(5)))),if(i<2)const SizedBox(width:5)]]);
  Widget _stepProduct()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
    GlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('1. PRODOTTO',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:12),Container(height:155,decoration:BoxDecoration(color:MercDealTheme.card2,borderRadius:BorderRadius.circular(18)),child:const Center(child:Icon(Icons.add_photo_alternate_outlined,size:52,color:MercDealTheme.green))),const SizedBox(height:12),TextField(controller:title,decoration:const InputDecoration(labelText:'Titolo annuncio',hintText:'Es. iPhone 14 Pro 128GB')),const SizedBox(height:10),const TextField(maxLines:4,decoration:InputDecoration(labelText:'Descrizione',hintText:'Descrivi condizioni, accessori e dettagli')),const SizedBox(height:10),const Text('Condizioni',style:TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:6),Wrap(spacing:7,children:[ChoiceChip(label:const Text('Nuovo'),selected:false,onSelected:(_){ }),ChoiceChip(label:const Text('Come nuovo'),selected:true,onSelected:(_){ }),ChoiceChip(label:const Text('Ottime'),selected:false,onSelected:(_){ }),ChoiceChip(label:const Text('Buone'),selected:false,onSelected:(_){ })])])),
    const SizedBox(height:14),GlowButton(label:'Avanti',icon:Icons.arrow_forward_rounded,onPressed:()=>setState(()=>step=1)),
  ]);
  Widget _stepMode()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[GlassCard(glow:true,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('2. COME VUOI VENDERLO?',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:12),_mode(0,Icons.shopping_cart_rounded,'Compralo subito','Prezzo fisso. L’acquirente può comprare subito.'),_mode(1,Icons.trending_down_rounded,'Asta al ribasso','Il prezzo scende ogni giorno fino al minimo che decidi.'),_mode(2,Icons.handshake_rounded,'Proposta libera','Ricevi offerte e scegli se accettarle, rifiutarle o controproporre.'),const SizedBox(height:8),const Text('📈 Asta al ribasso = maggiore visibilità gratuita nell’ecosistema MercDeal.',style:TextStyle(color:MercDealTheme.green,fontWeight:FontWeight.w800,fontSize:12))])),const SizedBox(height:14),Row(children:[Expanded(child:OutlinedButton(onPressed:()=>setState(()=>step=0),child:const Text('Indietro'))),const SizedBox(width:8),Expanded(child:GlowButton(label:'Avanti',icon:Icons.arrow_forward_rounded,onPressed:()=>setState(()=>step=2)))])]);
  Widget _mode(int value,IconData icon,String title,String sub)=>GestureDetector(onTap:()=>setState(()=>mode=value),child:Container(margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:mode==value?MercDealTheme.green.withValues(alpha:.09):Colors.transparent,borderRadius:BorderRadius.circular(18),border:Border.all(color:mode==value?MercDealTheme.green.withValues(alpha:.55):Colors.white10)),child:Row(children:[Icon(icon,color:mode==value?MercDealTheme.green:Colors.white60,size:28),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:16)),Text(sub,style:const TextStyle(color:Colors.white54,fontSize:11))])),Icon(mode==value?Icons.radio_button_checked:Icons.radio_button_off,color:mode==value?MercDealTheme.green:Colors.white30)])));
  Widget _stepPrice()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[GlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('3. PREZZO E CONSEGNA',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),if(mode==1)...[const SizedBox(height:12),Row(children:[Expanded(child:_num('Prezzo iniziale',start)),const SizedBox(width:8),Expanded(child:_num('Prezzo minimo',minimum))]),const SizedBox(height:10),_num('Decremento giornaliero',drop),const SizedBox(height:10),const Text('Durata annuncio',style:TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:5),const Wrap(spacing:8,children:[ChoiceChip(label:Text('7 giorni'),selected:false,onSelected:null),ChoiceChip(label:Text('15 giorni'),selected:true,onSelected:null),ChoiceChip(label:Text('30 giorni'),selected:false,onSelected:null)]),const SizedBox(height:10),Container(height:100,padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.black26,borderRadius:BorderRadius.circular(18)),child:Row(children:[Text('€${start.toStringAsFixed(2)}'),const Expanded(child:Divider(indent:12,endIndent:12,color:MercDealTheme.green)),Text('€${minimum.toStringAsFixed(2)}',style:const TextStyle(color:MercDealTheme.green,fontWeight:FontWeight.w900))])),],const SizedBox(height:12),const Text('Opzioni di consegna',style:TextStyle(fontWeight:FontWeight.w900)),SwitchListTile(contentPadding:EdgeInsets.zero,value:ship,onChanged:(v)=>setState(()=>ship=v),title:const Text('Spedizione'),subtitle:const Text('Corriere + tracking'),secondary:const Icon(Icons.local_shipping_outlined,color:MercDealTheme.green)),SwitchListTile(contentPadding:EdgeInsets.zero,value:pickup,onChanged:(v)=>setState(()=>pickup=v),title:const Text('Ritiro a mano'),subtitle:const Text('Punto scelto dal venditore'),secondary:const Icon(Icons.location_on_outlined,color:MercDealTheme.green))])),const SizedBox(height:14),GlowButton(label:'🚀 Pubblica annuncio',icon:Icons.rocket_launch_rounded,onPressed:()=>_publish(context)),const SizedBox(height:8),OutlinedButton.icon(onPressed:()=>setState(()=>step=1),icon:const Icon(Icons.arrow_back_rounded),label:const Text('Indietro'),style:OutlinedButton.styleFrom(minimumSize:const Size.fromHeight(48))) ]);
  Widget _num(String label,double value)=>TextField(keyboardType:TextInputType.number,decoration:InputDecoration(labelText:label,prefixText:'€ ',hintText:value.toStringAsFixed(2)));
  void _publish(BuildContext context){final listing=Listing(id:'new',title:title.text.isEmpty?'Il mio nuovo annuncio':title.text,category:'Elettronica',priceLabel:'€${minimum.toStringAsFixed(2).replaceAll('.',',')}',oldPriceLabel:'€${start.toStringAsFixed(2).replaceAll('.',',')}',dropLabel:'Asta',asset:'phone.png',location:'Italia',price:minimum,startPrice:start,minimumPrice:minimum,drop:drop,mode:mode==0?SaleMode.buyNow:mode==2?SaleMode.freeOffer:SaleMode.descendingAuction,condition:ListingCondition.likeNew,verifiedSeller:true,showcase:false,followers:0,offers:0);Navigator.push(context,MaterialPageRoute(builder:(_)=>ListingDetailScreen(listing:listing)));}
}
